-- Civi
TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.CIVI = {}

TUNING.CIVI_HEALTH = 175
TUNING.CIVI_HUNGER = 175
TUNING.CIVI_SANITY = 175

TUNING.STACK_SIZE_PLUSITEM = 8
-- Mio
TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.MIOTAN = {
    "nightmarefuel",
    "nightmarefuel",
    "nightmarefuel",
    "nightmarefuel"
}
TUNING.MIOTAN_HEALTH = 100
TUNING.MIOTAN_HUNGER = 100
TUNING.MIOTAN_SANITY = 100

-- Dummy
TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.DUMMY = {}
TUNING.DUMMY_HEALTH = 200
TUNING.DUMMY_HUNGER = 150
-- TUNING.DUMMY_SANITY = 250

-- spice_cactus --
TUNING.SPICE_MULTIPLIERS.SPICE_CACTUS = {
    SANITY = 1
}
