-- Civi --
TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.CIVI = {}

TUNING.CIVI_HEALTH = 175
TUNING.CIVI_HUNGER = 175
TUNING.CIVI_SANITY = 175

TUNING.STACK_SIZE_PLUSITEM = 8

-- Mio --
TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.MIOTAN = {
    "nightmarefuel",
    "nightmarefuel",
    "nightmarefuel",
    "nightmarefuel"
}
TUNING.MIOTAN_STATUS = 100
TUNING.MIOTAN_HEALTH = TUNING.MIOTAN_STATUS
TUNING.MIOTAN_HUNGER = TUNING.MIOTAN_STATUS
TUNING.MIOTAN_SANITY = TUNING.MIOTAN_STATUS

TUNING.MIOTAN_SANITY_DAPPERNESS = - 1/18
TUNING.MIOTAN_SANITY_MULT = - TUNING.WENDY_SANITY_MULT
TUNING.MIOTAN_SANITY_MULT = TUNING.WENDY_SANITY_MULT

-- Dummy --
TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.DUMMY = {}
TUNING.DUMMY_HEALTH = 200
TUNING.DUMMY_HUNGER = 150
TUNING.DUMMY_SANITY = TUNING.DUMMY_HEALTH

-- spice_cactus --
TUNING.SPICE_MULTIPLIERS.SPICE_CACTUS = {
    SANITY = 1
}
